import{lazy,Suspense,useEffect,useState}from'react';import{AnimatePresence,motion}from'framer-motion';import{NavLink,Route,Routes}from'react-router-dom';import{BedDouble,Brain,CalendarDays,Camera,ChevronLeft,ChevronRight,Heart,Home,LockKeyhole,MapPin,Menu,MessageCircle,Pause,Play,Users,X}from'lucide-react';import{guests,members,metDate,photos}from'./data';
const AbilityRadar=lazy(()=>import('./AbilityRadar'));
const GuestsPage=lazy(()=>import('./GuestsPage'));
const YearsPage=lazy(()=>import('./YearsPage'));
const MomentsPage=lazy(()=>import('./MomentsPage'));
const HeartsPage=lazy(()=>import('./HeartsPage'));
const MessagesPage=lazy(()=>import('./MessagesPage'));
const nav=[['/','总览',Home],['/members','主创',Users],['/years','纪年',CalendarDays],['/hearts','感情线',Heart],['/moments','名场面',Camera],['/guests','嘉宾',Users],['/messages','留言',MessageCircle]]as const;
function Layout(){const[open,setOpen]=useState(false);const[playing,setPlaying]=useState(false);useEffect(()=>{const a=document.querySelector('audio');playing?(a as HTMLAudioElement)?.play():(a as HTMLAudioElement)?.pause()},[playing]);return <div className="app"><nav className="nav"><NavLink to="/" className="logo"><b>C</b><span>C106<small>COLLECTIVE ARCHIVE</small></span></NavLink><div className={open?'links open':'links'}>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon size={15}/>{label}</NavLink>)}</div><button className="music" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}<span><b>Otto — It's a Vibe</b><small>{playing?'正在播放':'点击播放'}</small></span></button><button className="hamb" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><audio loop src="/media/bgm.mp3"/></nav><main><AnimatePresence mode="wait"><Routes><Route path="/" element={<Overview/>}/><Route path="/members" element={<Members/>}/><Route path="/years" element={<Years/>}/><Route path="/hearts" element={<Hearts/>}/><Route path="/moments" element={<Moments/>}/><Route path="/guests" element={<Guests/>}/><Route path="/messages" element={<Messages/>}/></Routes></AnimatePresence></main></div>}
const toWebp=(src:string)=>src.replace(/\.(png|jpg|jpeg)$/i,'.webp');
const resolvedImageSrc=(src:string)=>src.includes('-profile.')?toWebp(src):src;
type ImgProps=React.ImgHTMLAttributes<HTMLImageElement>&{src:string;priority?:boolean};
const Img=({src,className,priority=false,loading,...r}:ImgProps)=><img src={resolvedImageSrc(src)} className={className} loading={priority?'eager':loading??'lazy'} decoding="async" fetchPriority={priority?'high':'auto'} {...r}/>;const Page=({children,className=''}:{children:React.ReactNode,className?:string})=><motion.section className={`page ${className}`} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:.3}}>{children}</motion.section>;
const memberHeroCache=new Map<string,Promise<void>>();let heroLoadTail=Promise.resolve();
function preloadMemberHero(src:string){const url=toWebp(src);const cached=memberHeroCache.get(url);if(cached)return cached;const task=heroLoadTail=heroLoadTail.catch(()=>{}).then(()=>new Promise<void>((resolve,reject)=>{const image=new Image();image.onload=()=>{if(image.decode)image.decode().then(()=>resolve()).catch(()=>resolve());else resolve()};image.onerror=()=>reject(new Error(`Failed to preload ${url}`));image.src=url})).catch(error=>{memberHeroCache.delete(url);throw error});memberHeroCache.set(url,task);return task}
function Overview(){const allBgs=['/media/overview-bg.webp',...photos];const[index,setIndex]=useState(0);const[picker,setPicker]=useState(false);const getMinutes=()=>Math.floor((Date.now()-new Date(metDate).getTime())/60000);const[minutes,setMinutes]=useState(getMinutes);useEffect(()=>{const slideTimer=setInterval(()=>setIndex(v=>(v+1)%allBgs.length),7000);const minuteTimer=setInterval(()=>setMinutes(getMinutes()),10000);return()=>{clearInterval(slideTimer);clearInterval(minuteTimer)}},[]);useEffect(()=>{const preload=new Image();const start=()=>{preload.src=allBgs[(index+1)%allBgs.length]};if('requestIdleCallback'in window){const id=window.requestIdleCallback(start,{timeout:2500});return()=>window.cancelIdleCallback(id)}const id=globalThis.setTimeout(start,800);return()=>globalThis.clearTimeout(id)},[index]);return <Page className="overview"><div className="hero-bg"><Img key={allBgs[index]} className="active" src={allBgs[index]} priority/></div><div className="hero-shade"/><div className="overview-mark"><span>C106</span><small>COLLECTIVE ARCHIVE</small></div><div className="minute-counter"><p>从 2021.09.01 开始，我们已经相识</p><strong>{minutes.toLocaleString()}</strong><div><i/> MINUTES TOGETHER <i/></div></div><div className="overview-foot"><span>十个人 · 一段仍在继续的故事</span><em>EST. 2021</em></div><div className="bg-picker"><button onClick={()=>setPicker(!picker)}><Camera size={15}/></button>{picker&&<div className="bg-thumbs">{allBgs.map((p,i)=><button key={i} className={i===index?'active':''} onClick={()=>{setIndex(i);setPicker(false)}}><Img src={p}/></button>)}</div>}</div></Page>}
function Members(){const[active,setActive]=useState(0);const[collapsed,setCollapsed]=useState(false);const[visibleHero,setVisibleHero]=useState(members[0].hero);const[switching,setSwitching]=useState(false);const m=members[active];useEffect(()=>{if(!m.hero||visibleHero===m.hero){setSwitching(false);return}let current=true;setSwitching(true);preloadMemberHero(m.hero).then(()=>{if(current){setVisibleHero(m.hero);setSwitching(false)}}).catch(()=>{if(current){setVisibleHero(m.hero);setSwitching(false)}});return()=>{current=false}},[m.hero,visibleHero]);useEffect(()=>{const id=globalThis.setTimeout(()=>{for(const offset of[-1,1]){const next=members[(active+offset+members.length)%members.length];if(next.hero)void preloadMemberHero(next.hero).catch(()=>{})}},900);return()=>globalThis.clearTimeout(id)},[active]);return <Page className={`members-page${switching?' member-switching':''}`}>{visibleHero?<Img key={visibleHero} className="member-page-bg" src={visibleHero} priority style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<div className="member-page-bg"/>}<div className="member-page-shade"/><div className="member-strip">{members.map((x,i)=><button className={i===active?'active':''} onClick={()=>setActive(i)} onMouseEnter={()=>{if(x.hero)void preloadMemberHero(x.hero).catch(()=>{})}} onFocus={()=>{if(x.hero)void preloadMemberHero(x.hero).catch(()=>{})}} key={x.id}>{x.avatar?<Img src={x.avatar}/>:<span>{String(i+1).padStart(2,'0')}</span>}<div><b>{x.nickname}</b><small>{x.aliases.join('·')}</small></div></button>)}</div><section className="profile" aria-busy={switching}><div className="profile-watermark">{m.englishName}</div><button className="collapse" onClick={()=>setCollapsed(!collapsed)}>{collapsed?<ChevronLeft/>:<ChevronRight/>}</button><aside key={m.id} className={collapsed?'collapsed':''}><p className="profile-english">{m.englishName}</p><h2>{m.nickname}</h2><p className="profile-aliases">{m.aliases.join(' · ')}</p><blockquote>“{m.quote}”</blockquote><div className="profile-metrics"><div><BedDouble size={19}/><small>床号</small><strong>{m.bed}</strong></div><div><MapPin size={19}/><small>地區</small><strong>{m.region}</strong></div><div><Brain size={19}/><small>MBTI</small><strong>{m.mbti}</strong></div></div><div className="profile-lower"><div><h3>ABILITY RADAR</h3><Suspense fallback={<div className="radar"/>}><AbilityRadar stats={m.stats}/></Suspense></div><div className="profile-notes"><h3>PROFILE NOTES</h3><b>BUFFS</b><div className="effect-tags">{m.buffs.map(item=><span key={item}>{item}</span>)}</div><b>DEBUFFS</b><div className="effect-tags debuffs">{m.debuffs.map(item=><span key={item}>{item}</span>)}</div></div></div></aside></section></Page>}
function Years(){return <Suspense fallback={<div className="page"/>}><YearsPage/></Suspense>}
function Hearts(){return <Suspense fallback={<div className="page"/>}><HeartsPage members={members}/></Suspense>}
function Moments(){return <Suspense fallback={<div className="page"/>}><MomentsPage staticPhotos={photos}/></Suspense>}
function Guests(){return <Suspense fallback={<div className="page"/>}><GuestsPage staticGuests={guests}/></Suspense>}
function Messages(){return <Suspense fallback={<div className="page"/>}><MessagesPage/></Suspense>}
function Header({over,title,desc}:{over:string,title:string,desc:string}){return <header className="page-head"><div><p className="kicker">{over}</p><h1>{title}</h1></div><p>{desc}</p></header>}
export default Layout;
