export const metDate='2021-09-01T00:00:00+08:00';
export type MemberProfile={id:string;englishName:string;nickname:string;aliases:string[];quote:string;bed:string;region:string;mbti:string;avatar:string;hero:string;stats:{name:string;value:number}[];buffs:string[];debuffs:string[]};
export const members:MemberProfile[]=[
 {id:'lingard',englishName:'LINGARD',nickname:'林加德',aliases:['教练','🌽','阿铭'],quote:'故事还没有结束，我们只是刚刚开始整理。',bed:'3',region:'重慶',mbti:'ENFP',avatar:'/media/lingard-avatar.jpg',hero:'/media/lingard-profile.png',stats:[{name:'行动力',value:75},{name:'默契',value:50},{name:'组织力',value:90},{name:'镜头感',value:80},{name:'运气',value:60},{name:'活跃',value:200}],buffs:['心情好的时候运气+99'],debuffs:['心情不好时所有数据-50']},
 {id:'bayern',englishName:'BAYERN',nickname:'槽阻',aliases:['状元','欧gia','🏠'],quote:'惊艳！',bed:'10',region:'天津',mbti:'INFP',avatar:'/media/member-02-bayern-avatar.jpg',hero:'/media/member-02-bayern-profile.png',stats:[{name:'行动力',value:80},{name:'默契',value:90},{name:'组织力',value:75},{name:'镜头感',value:40},{name:'运气',value:88},{name:'活跃',value:100}],buffs:['待填写'],debuffs:['待填写']},
 {id:'melon',englishName:'MELON',nickname:'西瓜',aliases:['晋洗','🍉','舍长'],quote:'舍长请吃汉堡，前年拿下高考。',bed:'2',region:'廈門',mbti:'INFJ',avatar:'/media/member-03-melon-avatar.jpg',hero:'/media/member-03-melon-profile.png',stats:[{name:'行动力',value:81},{name:'默契',value:66},{name:'组织力',value:65},{name:'镜头感',value:70},{name:'运气',value:88},{name:'活跃',value:75}],buffs:['待填写'],debuffs:['待填写']},
 {id:'cech',englishName:'CECH',nickname:'小贺',aliases:['阿坤','🐓','鸟蛋生成者'],quote:'明哥，梅西进球了啊？明哥！',bed:'1',region:'北京',mbti:'待填写',avatar:'/media/member-04-cech-avatar.jpg',hero:'/media/member-04-cech-profile.png',stats:[{name:'行动力',value:80},{name:'默契',value:90},{name:'组织力',value:30},{name:'镜头感',value:88},{name:'运气',value:90},{name:'活跃',value:10}],buffs:['待填写'],debuffs:['待填写']},
 {id:'longteng',englishName:'LONGTENG',nickname:'凉亭',aliases:['龙队','⏹'],quote:'待填写',bed:'6',region:'海口',mbti:'isfp',avatar:'/media/member-05-longteng-avatar.jpg',hero:'/media/member-05-longteng-profile.png',stats:[{name:'行动力',value:90},{name:'默契',value:75},{name:'组织力',value:80},{name:'镜头感',value:80},{name:'运气',value:99},{name:'活跃',value:60}],buffs:['待填写'],debuffs:['待填写']},
 {id:'leng',englishName:'LENG',nickname:'网楞',aliases:['主席'],quote:'待填写',bed:'5',region:'北京',mbti:'ESFP',avatar:'/media/member-06-leng-avatar.jpg',hero:'/media/member-06-leng-profile.png',stats:[{name:'行动力',value:90},{name:'默契',value:50},{name:'组织力',value:88},{name:'镜头感',value:90},{name:'运气',value:80},{name:'活跃',value:77}],buffs:['待填写'],debuffs:['待填写']},
 {id:'eason-gavi',englishName:'EASON GAVI',nickname:'医生',aliases:['加维'],quote:'我想谈恋爱了',bed:'9',region:'重慶',mbti:'INFP',avatar:'/media/member-07-eason-gavi-avatar.jpg',hero:'/media/member-07-eason-gavi-profile.png',stats:[{name:'行动力',value:10},{name:'默契',value:60},{name:'组织力',value:20},{name:'镜头感',value:90},{name:'运气',value:20},{name:'活跃',value:0}],buffs:['待填写'],debuffs:['待填写']},
 {id:'maldini',englishName:'MALDINI',nickname:'小马',aliases:['长远','log','🐎'],quote:'待填写',bed:'7',region:'河北',mbti:'esfj',avatar:'/media/member-08-maldini-avatar.jpg',hero:'/media/member-08-maldini-profile.png',stats:[{name:'行动力',value:88},{name:'默契',value:20},{name:'组织力',value:90},{name:'镜头感',value:20},{name:'运气',value:66},{name:'活跃',value:70}],buffs:['待填写'],debuffs:['待填写']},
 {id:'loong',englishName:'LOONG',nickname:'杰根李',aliases:['小美'],quote:'待填写',bed:'8',region:'北京',mbti:'忘了',avatar:'/media/member-09-loong-avatar.jpg',hero:'/media/member-09-loong-profile.png',stats:[{name:'行动力',value:20},{name:'默契',value:80},{name:'组织力',value:20},{name:'镜头感',value:5},{name:'运气',value:70},{name:'活跃',value:20}],buffs:['待填写'],debuffs:['待填写']},
 {id:'issac',englishName:'ISSAC',nickname:'魏端',aliases:['竹竿'],quote:'待填写',bed:'4',region:'北京',mbti:'ISTP',avatar:'/media/member-10-issac-avatar.jpg',hero:'/media/member-10-issac-profile.png',stats:[{name:'行动力',value:50},{name:'默契',value:80},{name:'组织力',value:10},{name:'镜头感',value:88},{name:'运气',value:88},{name:'活跃',value:88}],buffs:['待填写'],debuffs:['待填写']}
];
export const photos=['/media/group-1.jpg','/media/group-2.jpg','/media/group-3.jpg','/media/group-4.jpg','/media/group-5.jpg'];
export const years=[2021,2022,2023,2024,2025,2026];
export const events:Record<number,{date:string;title:string;place:string;members:number[]}[]>={
2021:[{date:'09.01',title:'故事从这里开始',place:'待补充地点',members:[0,1,2,3,4,5,6,7,8,9]}],2022:[{date:'春',title:'2022 年共同活动',place:'待补充',members:[0,2,4,6]}],2023:[{date:'11.18',title:'镜头留下的一天',place:'共同记忆',members:[0,1,3,5,8]}],2024:[{date:'06.10',title:'夏日集合',place:'共同记忆',members:[0,1,2,3,4,5,6,7,8,9]},{date:'09.27',title:'秋日合照',place:'共同记忆',members:[0,2,4,6,8]}],2025:[{date:'08',title:'又一次全员出现',place:'共同记忆',members:[0,1,2,3,4,5,6,7,8,9]}],2026:[{date:'07.18',title:'共同图鉴开始制作',place:'线上',members:[0]}]};
export const guests:never[]=[];
