import{useCallback,useEffect,useRef,useState}from'react';
import{ImagePlus,LoaderCircle,Pencil,Plus,Quote,Trash2,X}from'lucide-react';
import'./guests.css';

type Guest={id?:number;alias:string;desc:string;avatar?:string;tags?:string;quote?:string;created_at?:string};
type GuestForm={alias:string;desc:string;avatar:string;tags:string;quote:string};
type CropState={src:string;width:number;height:number;zoom:number;x:number;y:number};
const EMPTY_FORM:GuestForm={alias:'',desc:'',avatar:'',tags:'',quote:''};
const MAX_AVATAR_BYTES=80*1024;
const CROP_SIZE=300;

function readAsDataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('头像读取失败'));reader.readAsDataURL(blob)})}
function canvasBlob(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法转换这张图片')),'image/webp',quality))}
function loadImageSource(src:string){return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('无法识别这张图片'));image.src=src})}
function cropLimits(crop:CropState,zoom=crop.zoom){const scale=Math.max(CROP_SIZE/crop.width,CROP_SIZE/crop.height)*zoom;return{x:Math.max(0,(crop.width*scale-CROP_SIZE)/2),y:Math.max(0,(crop.height*scale-CROP_SIZE)/2),scale}}
async function cropAvatar(crop:CropState){
 const image=await loadImageSource(crop.src);const limits=cropLimits(crop);const sourceSize=CROP_SIZE/limits.scale;const sourceX=Math.max(0,Math.min(crop.width-sourceSize,(crop.width-sourceSize)/2-crop.x/limits.scale));const sourceY=Math.max(0,Math.min(crop.height-sourceSize,(crop.height-sourceSize)/2-crop.y/limits.scale));const canvas=document.createElement('canvas');const ctx=canvas.getContext('2d');if(!ctx)throw new Error('浏览器不支持图片裁切');const qualities=[.92,.86,.8,.74,.68,.6,.52,.44];
 for(const outputSize of[400,360,320,280]){canvas.width=outputSize;canvas.height=outputSize;ctx.clearRect(0,0,outputSize,outputSize);ctx.drawImage(image,sourceX,sourceY,sourceSize,sourceSize,0,0,outputSize,outputSize);for(const quality of qualities){const blob=await canvasBlob(canvas,quality);if(blob.size<=MAX_AVATAR_BYTES)return readAsDataUrl(blob)}}
 throw new Error('图片内容过于复杂，压缩后仍超过 80KB，请换一张图片');
}

export default function GuestsPage({staticGuests}:{staticGuests:{alias:string;desc:string}[]}){
 const[apiGuests,setApiGuests]=useState<Guest[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('');const[modalOpen,setModalOpen]=useState(false);const[editing,setEditing]=useState<Guest|null>(null);const[form,setForm]=useState<GuestForm>(EMPTY_FORM);const[saving,setSaving]=useState(false);const[imageBusy,setImageBusy]=useState(false);const[crop,setCrop]=useState<CropState|null>(null);const drag=useRef<{pointerId:number;startX:number;startY:number;x:number;y:number}|null>(null);
 const loadGuests=useCallback(async()=>{try{const response=await fetch('/api/guests',{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('暂时无法连接嘉宾数据库');const data=await response.json()as{guests?:Guest[]};setApiGuests(Array.isArray(data.guests)?data.guests:[]);setNotice('')}catch(error){setNotice(error instanceof Error?error.message:'嘉宾数据库加载失败')}finally{setLoading(false)}},[]);
 useEffect(()=>{void loadGuests()},[loadGuests]);
 useEffect(()=>{if(!modalOpen)return;const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!saving){if(crop)setCrop(null);else setModalOpen(false)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[crop,modalOpen,saving]);
 const openAdd=()=>{setEditing(null);setForm(EMPTY_FORM);setNotice('');setModalOpen(true)};
 const openEdit=(guest:Guest)=>{setEditing(guest);setForm({alias:guest.alias,desc:guest.desc||'',avatar:guest.avatar||'',tags:guest.tags||'',quote:guest.quote||''});setNotice('');setModalOpen(true)};
 const chooseAvatar=async(file?:File)=>{if(!file)return;setImageBusy(true);setNotice('');try{const src=await readAsDataUrl(file);const image=await loadImageSource(src);setCrop({src,width:image.naturalWidth,height:image.naturalHeight,zoom:1,x:0,y:0})}catch(error){setNotice(error instanceof Error?error.message:'头像处理失败')}finally{setImageBusy(false)}};
 const applyCrop=async()=>{if(!crop)return;setImageBusy(true);setNotice('');try{const avatar=await cropAvatar(crop);setForm(current=>({...current,avatar}));setCrop(null)}catch(error){setNotice(error instanceof Error?error.message:'头像处理失败')}finally{setImageBusy(false)}};
 const startDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(!crop)return;event.currentTarget.setPointerCapture(event.pointerId);drag.current={pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,x:crop.x,y:crop.y}};
 const moveDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(!crop||!drag.current||drag.current.pointerId!==event.pointerId)return;const limits=cropLimits(crop);const x=Math.max(-limits.x,Math.min(limits.x,drag.current.x+event.clientX-drag.current.startX));const y=Math.max(-limits.y,Math.min(limits.y,drag.current.y+event.clientY-drag.current.startY));setCrop({...crop,x,y})};
 const stopDrag=(event:React.PointerEvent<HTMLDivElement>)=>{if(drag.current?.pointerId===event.pointerId)drag.current=null};
 const setCropZoom=(zoom:number)=>setCrop(current=>{if(!current)return current;const limits=cropLimits(current,zoom);return{...current,zoom,x:Math.max(-limits.x,Math.min(limits.x,current.x)),y:Math.max(-limits.y,Math.min(limits.y,current.y))}});
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!form.alias.trim()||saving||imageBusy)return;setSaving(true);setNotice('');try{const editingId=editing?.id;const response=await fetch(editingId?`/api/guests/${editingId}`:'/api/guests',{method:editingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,alias:form.alias.trim(),desc:form.desc.trim(),tags:form.tags.trim(),quote:form.quote.trim()})});const data=await response.json().catch(()=>({}))as{error?:string};if(!response.ok)throw new Error(data.error||'保存失败，请稍后重试');await loadGuests();setModalOpen(false)}catch(error){setNotice(error instanceof Error?error.message:'保存失败，请稍后重试')}finally{setSaving(false)}};
 const removeGuest=async()=>{if(!editing?.id||saving||!window.confirm(`确定删除「${editing.alias}」吗？`))return;setSaving(true);setNotice('');try{const response=await fetch(`/api/guests/${editing.id}`,{method:'DELETE'});const data=await response.json().catch(()=>({}))as{error?:string};if(!response.ok)throw new Error(data.error||'删除失败');await loadGuests();setModalOpen(false)}catch(error){setNotice(error instanceof Error?error.message:'删除失败')}finally{setSaving(false)}};
 return <section className="page guests-editor-page">
  <header className="guests-editor-head"><div><p className="kicker">PEOPLE WE MET</p><h1>特别嘉宾</h1></div><div className="guests-editor-intro"><p>只显示外号和相遇描述，不公开真实姓名。</p><button className="guest-add" onClick={openAdd}><Plus size={17}/>添加嘉宾</button></div></header>
  {notice&&!modalOpen&&<p className="guest-notice" role="status">{notice}，静态档案仍可正常浏览。</p>}
  <div className="guest-editor-grid">
   {apiGuests.map((guest,index)=><article className="guest-editor-card" key={guest.id}><div className="guest-card-top"><span>{String(staticGuests.length+index+1).padStart(2,'0')}</span><button onClick={()=>openEdit(guest)} aria-label={`编辑 ${guest.alias}`}><Pencil size={14}/>编辑</button></div><div className="guest-card-main"><div className={`guest-editor-avatar ${guest.avatar?'has-image':''}`}>{guest.avatar?<img src={guest.avatar} alt="" loading="lazy" decoding="async"/>:'?'}</div><div className="guest-card-copy"><h3>「{guest.alias}」</h3><p>{guest.desc}</p>{guest.quote&&<blockquote><Quote size={14}/>{guest.quote}</blockquote>}</div></div><div className="guest-card-footer"><div className="guest-tags">{guest.tags?guest.tags.split(/[,，]/).map(tag=>tag.trim()).filter(Boolean).map((tag,tagIndex)=><span key={`${tag}-${tagIndex}`}>{tag}</span>):<span className="guest-no-tags">暂无标签</span>}</div></div></article>)}
   {loading&&<article className="guest-editor-card guest-loading"><LoaderCircle className="spin"/><p>正在读取嘉宾档案…</p></article>}
  </div>
  {modalOpen&&<div className="guest-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setModalOpen(false)}}><div className="guest-modal" role="dialog" aria-modal="true" aria-labelledby="guest-form-title"><div className="guest-modal-head"><div><p className="kicker">GUEST ARCHIVE</p><h2 id="guest-form-title">{editing?'编辑嘉宾':'添加嘉宾'}</h2></div><button className="guest-modal-close" onClick={()=>setModalOpen(false)} disabled={saving} aria-label="关闭"><X/></button></div><form onSubmit={submit}>
   <label><span>别名 *</span><input required maxLength={80} value={form.alias} onChange={event=>setForm({...form,alias:event.target.value})} placeholder="嘉宾的公开称呼"/></label>
   <label><span>描述</span><textarea maxLength={2000} rows={4} value={form.desc} onChange={event=>setForm({...form,desc:event.target.value})} placeholder="记录与这位嘉宾相遇的故事"/></label>
   <label><span>Tag</span><input maxLength={500} value={form.tags} onChange={event=>setForm({...form,tags:event.target.value})} placeholder="朋友, 旅途, 2026（逗号分隔）"/></label>
   <label><span>名言</span><input maxLength={500} value={form.quote} onChange={event=>setForm({...form,quote:event.target.value})} placeholder="留下一句代表性的话"/></label>
   <label className="guest-avatar-field"><span>头像</span><div className="guest-avatar-input">{form.avatar?<img src={form.avatar} alt="头像预览"/>:<ImagePlus size={28}/>}<div><b>{imageBusy?'正在处理…':form.avatar?'更换头像':'选择并裁切头像'}</b><small>裁切后自动转为 WebP，最大 400×400、80KB</small></div><input type="file" accept="image/*" disabled={imageBusy||saving} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';void chooseAvatar(file)}}/></div>{form.avatar&&<button type="button" className="guest-remove-avatar" onClick={()=>setForm({...form,avatar:''})}>移除头像</button>}</label>
   {notice&&<p className="guest-form-error" role="alert">{notice}</p>}
   <div className="guest-form-actions">{editing&&<button type="button" className="guest-delete" onClick={removeGuest} disabled={saving}><Trash2 size={16}/>删除</button>}<span/><button type="button" className="guest-cancel" onClick={()=>setModalOpen(false)} disabled={saving}>取消</button><button className="guest-save" disabled={saving||imageBusy||!form.alias.trim()}>{saving?<><LoaderCircle className="spin" size={17}/>保存中…</>:editing?'保存修改':'添加嘉宾'}</button></div>
  </form></div></div>}
  {crop&&<div className="guest-crop-backdrop"><div className="guest-crop-dialog" role="dialog" aria-modal="true" aria-labelledby="guest-crop-title"><div className="guest-crop-head"><div><p className="kicker">IMAGE CROP</p><h2 id="guest-crop-title">裁切头像</h2></div><button onClick={()=>setCrop(null)} aria-label="关闭裁切"><X/></button></div><p>拖动图片选择上传区域，使用滑杆缩放；确认后会自动转成 WebP 并压缩。</p><div className="guest-crop-stage" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={stopDrag} onPointerCancel={stopDrag}><img src={crop.src} alt="待裁切图片" draggable={false} style={{width:crop.width*cropLimits(crop).scale,height:crop.height*cropLimits(crop).scale,transform:`translate(calc(-50% + ${crop.x}px),calc(-50% + ${crop.y}px))`}}/><div className="guest-crop-frame"/></div><label className="guest-crop-zoom"><span>缩放</span><input type="range" min="1" max="3" step="0.01" value={crop.zoom} onChange={event=>setCropZoom(Number(event.target.value))}/></label><div className="guest-crop-actions"><button className="guest-cancel" onClick={()=>setCrop(null)} disabled={imageBusy}>取消</button><button className="guest-save" onClick={()=>void applyCrop()} disabled={imageBusy}>{imageBusy?<><LoaderCircle className="spin" size={17}/>处理中…</>:'使用此裁切'}</button></div></div></div>}
 </section>
}
