import{useCallback,useEffect,useMemo,useState}from'react';
import{Heart,LoaderCircle,LockKeyhole}from'lucide-react';
void import('./hearts.css');

type Member={id:string;nickname:string;avatar?:string};type HeartRecord={member_id:string;period:string;status:string};
const OPTIONS=[['unknown','❔','未知'],['single','💚','单身'],['dating','💞','恋爱'],['crush','🌱','暧昧'],['breakup','💔','分手'],['private','🌫️','保密']]as const;
function periodsThroughNow(){const now=new Date();const endYear=now.getFullYear();const endHalf=now.getMonth()<6?1:2;const periods:string[]=[];for(let year=2021;year<=endYear;year++){for(let half=1;half<=2;half++){if(year===2021&&half===1)continue;if(year===endYear&&half>endHalf)continue;periods.push(`${year}-H${half}`)}}return periods}
function labelOf(period:string){const[year,half]=period.split('-');return`${year}${half==='H1'?'上':'下'}`}
export default function HeartsPage({members}:{members:Member[]}){const[key,setKey]=useState(()=>sessionStorage.getItem('heart-key')||'');const[unlocked,setUnlocked]=useState(Boolean(key));const[input,setInput]=useState('');const[records,setRecords]=useState<Record<string,string>>({});const[notice,setNotice]=useState('');const[loading,setLoading]=useState(false);const[saving,setSaving]=useState('');const[clock,setClock]=useState(Date.now());const periods=useMemo(periodsThroughNow,[clock]);
 const load=useCallback(async(secret=key)=>{setLoading(true);try{const response=await fetch('/api/hearts',{headers:{'X-Archive-Key':secret}});const data=await response.json()as{statuses?:HeartRecord[],error?:string};if(!response.ok)throw new Error(data.error||'感情线读取失败');const next:Record<string,string>={};for(const item of data.statuses||[])next[`${item.member_id}|${item.period}`]=item.status;setRecords(next);setNotice('');return true}catch(error){setNotice(error instanceof Error?error.message:'感情线读取失败');return false}finally{setLoading(false)}},[key]);useEffect(()=>{if(unlocked)void load()},[load,unlocked]);useEffect(()=>{const timer=globalThis.setInterval(()=>setClock(Date.now()),60*60*1000);return()=>globalThis.clearInterval(timer)},[]);
 const unlock=async(event:React.FormEvent)=>{event.preventDefault();const secret=input.trim();if(!secret)return;const valid=await load(secret);if(valid){sessionStorage.setItem('heart-key',secret);setKey(secret);setUnlocked(true)}};const update=async(memberId:string,period:string,status:string)=>{const recordKey=`${memberId}|${period}`;const previous=records[recordKey]||'unknown';setRecords(current=>({...current,[recordKey]:status}));setSaving(recordKey);try{const response=await fetch('/api/hearts',{method:'PUT',headers:{'Content-Type':'application/json','X-Archive-Key':key},body:JSON.stringify({member_id:memberId,period,status})});const data=await response.json()as{error?:string};if(!response.ok)throw new Error(data.error||'保存失败');setNotice('')}catch(error){setRecords(current=>({...current,[recordKey]:previous}));setNotice(error instanceof Error?error.message:'保存失败')}finally{setSaving('')}};
 if(!unlocked)return <section className="page hearts-lock"><div className="heart-lock-card"><LockKeyhole size={42}/><p className="kicker">PRIVATE TIMELINE</p><h1>感情线</h1><p>这是一份只对成员开放的半年状态档案。</p><form onSubmit={unlock}><input type="password" value={input} onChange={event=>setInput(event.target.value)} placeholder="输入访问口令" autoFocus/><button disabled={loading}>{loading?<LoaderCircle className="spin"/>:'解锁'}</button></form>{notice&&<small>{notice}</small>}</div></section>;
 return <section className="page hearts-page"><header className="hearts-head"><div><p className="kicker">RELATIONSHIP TIMELINE</p><h1>感情线</h1><p>从 2021 下半年开始，每半年记录一次。点击任意状态即可更新。</p></div><div className="heart-legend">{OPTIONS.map(([,emoji,label])=><span key={label}>{emoji} {label}</span>)}</div></header>{notice&&<p className="hearts-notice">{notice}</p>}<div className="heart-timeline" style={{'--period-count':periods.length}as React.CSSProperties}><div className="heart-row heart-periods"><b><Heart size={16}/>成员</b>{periods.map(period=><span key={period}>{labelOf(period)}</span>)}</div>{members.map(member=><div className="heart-row" key={member.id}><b>{member.avatar&&<img src={member.avatar} alt=""/>}<span>{member.nickname}</span></b>{periods.map(period=>{const recordKey=`${member.id}|${period}`;const value=records[recordKey]||'unknown';return <label className={`heart-cell status-${value}${saving===recordKey?' saving':''}`} key={period}><select value={value} disabled={saving===recordKey} onChange={event=>void update(member.id,period,event.target.value)} aria-label={`${member.nickname} ${labelOf(period)}状态`}>{OPTIONS.map(([status,emoji,label])=><option value={status} key={status}>{emoji} {label}</option>)}</select></label>})}</div>)}</div></section>}
