import{useCallback,useEffect,useMemo,useState}from'react';
import{ImagePlus,LoaderCircle,Pencil,Plus,Trash2,X}from'lucide-react';
void import('./moments.css');

type Moment={id?:number;title:string;image:string;created_at?:string};
const MAX_IMAGE_BYTES=160*1024;
const EMPTY={title:'',image:''};

function blobOf(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法处理照片')),'image/webp',quality))}
function dataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('照片读取失败'));reader.readAsDataURL(blob)})}
function loadImage(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(file);const image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('无法识别这张照片'))};image.src=url})}
async function optimizeImage(file:File){
 const image=await loadImage(file);const sourceRatio=image.naturalWidth/image.naturalHeight;const targetRatio=16/9;let sx=0,sy=0,sw=image.naturalWidth,sh=image.naturalHeight;if(sourceRatio>targetRatio){sw=Math.round(sh*targetRatio);sx=Math.round((image.naturalWidth-sw)/2)}else{sh=Math.round(sw/targetRatio);sy=Math.round((image.naturalHeight-sh)/2)}const canvas=document.createElement('canvas');const context=canvas.getContext('2d');if(!context)throw new Error('浏览器不支持照片处理');
 for(const width of[1280,1120,960,800]){canvas.width=width;canvas.height=Math.round(width/targetRatio);context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(image,sx,sy,sw,sh,0,0,canvas.width,canvas.height);for(const quality of[.86,.78,.7,.62,.54,.46]){const blob=await blobOf(canvas,quality);if(blob.size<=MAX_IMAGE_BYTES)return dataUrl(blob)}}throw new Error('照片处理后仍超过 160KB，请换一张照片');
}

function FilmCard({moment,editable,onEdit}:{moment:Moment;editable:boolean;onEdit:(moment:Moment)=>void}){return <figure className="film-card"><img src={moment.image} alt={moment.title} loading="lazy" decoding="async"/><figcaption>{moment.title}</figcaption>{editable&&moment.id&&<button onClick={()=>onEdit(moment)} aria-label={`编辑${moment.title}`}><Pencil size={14}/></button>}</figure>}

export default function MomentsPage({staticPhotos}:{staticPhotos:string[]}){
 const[apiMoments,setApiMoments]=useState<Moment[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('');const[editMode,setEditMode]=useState(false);const[modal,setModal]=useState(false);const[editing,setEditing]=useState<Moment|null>(null);const[form,setForm]=useState(EMPTY);const[saving,setSaving]=useState(false);const[imageBusy,setImageBusy]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch('/api/moments',{headers:{Accept:'application/json'}});const data=await response.json()as{moments?:Moment[],error?:string};if(!response.ok)throw new Error(data.error||'照片加载失败');setApiMoments(data.moments||[]);setNotice('')}catch(error){setNotice(error instanceof Error?error.message:'照片加载失败')}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(!editMode)return;const exit=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!modal)setEditMode(false)};window.addEventListener('keydown',exit);return()=>window.removeEventListener('keydown',exit)},[editMode,modal]);
 const moments=useMemo<Moment[]>(()=>[...staticPhotos.map((image,index)=>({title:`场景${String(index+1).padStart(2,'0')}`,image})),...apiMoments],[apiMoments,staticPhotos]);
 const laneItems=useMemo(()=>Array.from({length:Math.max(10,moments.length*2)},(_,index)=>moments[index%moments.length]).filter(Boolean),[moments]);
 const openAdd=()=>{setEditing(null);setForm(EMPTY);setNotice('');setModal(true)};const openEdit=(moment:Moment)=>{setEditing(moment);setForm({title:moment.title,image:moment.image});setNotice('');setModal(true)};
 const chooseImage=async(file?:File)=>{if(!file)return;setImageBusy(true);setNotice('');try{const image=await optimizeImage(file);setForm(current=>({...current,image}))}catch(error){setNotice(error instanceof Error?error.message:'照片处理失败')}finally{setImageBusy(false)}};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if([...form.title.trim()].length>7){setNotice('小标题不能超过 7 个字');return}setSaving(true);setNotice('');try{const response=await fetch(editing?.id?`/api/moments/${editing.id}`:'/api/moments',{method:editing?.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json()as{error?:string};if(!response.ok)throw new Error(data.error||'保存失败');setModal(false);await load()}catch(error){setNotice(error instanceof Error?error.message:'保存失败')}finally{setSaving(false)}};
 const remove=async()=>{if(!editing?.id||!confirm('确定删除这张照片吗？'))return;setSaving(true);try{const response=await fetch(`/api/moments/${editing.id}`,{method:'DELETE'});const data=await response.json()as{error?:string};if(!response.ok)throw new Error(data.error||'删除失败');setModal(false);await load()}catch(error){setNotice(error instanceof Error?error.message:'删除失败')}finally{setSaving(false)}};
 return <section className="page moments-page"><header className="moments-head"><div><p className="kicker">ICONIC MOMENTS</p><h1>名场面</h1><p>三卷持续转动的记忆胶片，把共同经历留在每一格画面里。</p></div><img className="moments-lineup" src="/media/moments-lineup.webp" alt="十位成员的 Minecraft 人物合影" decoding="async"/><div className="moments-tools"><button className={editMode?'active':''} onClick={()=>setEditMode(value=>!value)}><Pencil size={16}/>{editMode?'退出编辑':'编辑模式'}</button>{editMode&&<button className="moment-add" onClick={openAdd}><Plus size={17}/>添加照片</button>}</div></header>{notice&&<p className="moments-notice">{notice}</p>}{loading?<div className="moments-loading"><LoaderCircle className="spin"/>照片装片中…</div>:<div className="film-reels">{[0,1,2].map(row=>{const shifted=[...laneItems.slice(row*2),...laneItems.slice(0,row*2)];return <div className={`film-reel row-${row+1}`} key={row}><div className="film-track">{[0,1].map(copy=><div className="film-group" data-copy={copy} key={copy}>{shifted.map((moment,index)=><FilmCard key={`${copy}-${index}-${moment.id??moment.title}`} moment={moment} editable={editMode} onEdit={openEdit}/>)}</div>)}</div></div>})}</div>}
 {modal&&<div className="moment-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!saving)setModal(false)}}><div className="moment-modal" role="dialog" aria-modal="true"><header><div><p className="kicker">FILM FRAME</p><h2>{editing?'编辑照片':'添加照片'}</h2></div><button onClick={()=>setModal(false)} aria-label="关闭"><X/></button></header><form onSubmit={submit}><label><span>小标题（不超过 7 个字）</span><input required maxLength={7} value={form.title} onChange={event=>setForm({...form,title:event.target.value})} placeholder="例如：夏日集合"/></label><label><span>照片</span><div className="moment-image-input">{form.image?<img src={form.image} alt="预览"/>:<ImagePlus size={30}/>}<div><b>{imageBusy?'正在处理…':form.image?'更换照片':'选择照片'}</b><small>自动裁切为 16:9 WebP，最大 160KB</small></div><input type="file" accept="image/*" disabled={imageBusy||saving} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';void chooseImage(file)}}/></div></label>{notice&&<p className="moment-form-error">{notice}</p>}<div className="moment-actions">{editing&&<button type="button" className="moment-delete" onClick={()=>void remove()} disabled={saving}><Trash2 size={15}/>删除</button>}<span/><button type="button" onClick={()=>setModal(false)} disabled={saving}>取消</button><button className="moment-save" disabled={saving||imageBusy||!form.image}>{saving?<LoaderCircle className="spin" size={16}/>:null}保存</button></div></form></div></div>}
 </section>;
}
