import{useCallback,useEffect,useMemo,useState}from'react';
import{ExternalLink,ImagePlus,LoaderCircle,Pencil,Plus,Trash2,X}from'lucide-react';
import{members}from'./data';
import'./years.css';

type TimelineEvent={id:number;event_date:string;title:string;place:string;participant_ids:string|string[];image:string;link:string;created_at?:string};
type EventForm={event_date:string;title:string;place:string;participant_ids:string[];image:string;link:string};
const EMPTY:EventForm={event_date:new Date().toISOString().slice(0,10),title:'',place:'',participant_ids:[],image:'',link:''};
const MAX_IMAGE_BYTES=220*1024;
function participantsOf(event:TimelineEvent){if(Array.isArray(event.participant_ids))return event.participant_ids;try{const parsed=JSON.parse(event.participant_ids||'[]');return Array.isArray(parsed)?parsed.map(String):[]}catch{return[]}}
function blobOf(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('浏览器无法处理图片')),'image/webp',quality))}
function dataUrl(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('图片读取失败'));reader.readAsDataURL(blob)})}
function loadImage(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(file);const image=new Image();image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('无法识别该图片'))};image.src=url})}
async function optimizeImage(file:File){const image=await loadImage(file);for(const maxWidth of[1280,1120,960,800]){const scale=Math.min(1,maxWidth/image.naturalWidth,720/image.naturalHeight);const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.naturalWidth*scale));canvas.height=Math.max(1,Math.round(image.naturalHeight*scale));canvas.getContext('2d')?.drawImage(image,0,0,canvas.width,canvas.height);for(const quality of[.88,.8,.72,.64,.56,.48]){const blob=await blobOf(canvas,quality);if(blob.size<=MAX_IMAGE_BYTES)return dataUrl(blob)}}throw new Error('图片压缩后仍超过 220KB，请选择内容更简单的图片')}

export default function YearsPage(){
 const[items,setItems]=useState<TimelineEvent[]>([]);const[year,setYear]=useState(new Date().getFullYear());const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('');const[modal,setModal]=useState(false);const[editing,setEditing]=useState<TimelineEvent|null>(null);const[form,setForm]=useState<EventForm>(EMPTY);const[saving,setSaving]=useState(false);const[imageBusy,setImageBusy]=useState(false);
 const load=useCallback(async()=>{try{const response=await fetch('/api/events',{headers:{Accept:'application/json'}});const data=await response.json()as{events?:TimelineEvent[],error?:string};if(!response.ok)throw new Error(data.error||'纪年数据加载失败');const sorted=(data.events||[]).sort((a,b)=>a.event_date.localeCompare(b.event_date)||a.id-b.id);setItems(sorted);if(sorted.length&&!sorted.some(item=>item.event_date.startsWith(String(year))))setYear(Number(sorted[0].event_date.slice(0,4)));setNotice('')}catch(error){setNotice(error instanceof Error?error.message:'纪年数据加载失败')}finally{setLoading(false)}},[year]);
 useEffect(()=>{void load()},[load]);
 const availableYears=useMemo(()=>[...new Set(items.map(item=>Number(item.event_date.slice(0,4))))].sort((a,b)=>a-b),[items]);const visible=items.filter(item=>item.event_date.startsWith(String(year)));
 const openAdd=()=>{setEditing(null);setForm({...EMPTY,event_date:`${year}-01-01`});setNotice('');setModal(true)};
 const openEdit=(event:TimelineEvent)=>{setEditing(event);setForm({event_date:event.event_date,title:event.title,place:event.place||'',participant_ids:participantsOf(event),image:event.image||'',link:event.link||''});setNotice('');setModal(true)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(saving||imageBusy||!form.title.trim())return;setSaving(true);setNotice('');try{const response=await fetch(editing?`/api/events/${editing.id}`:'/api/events',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,title:form.title.trim(),place:form.place.trim(),link:form.image?form.link.trim():''})});const data=await response.json().catch(()=>({}))as{error?:string};if(!response.ok)throw new Error(data.error||'保存失败');setYear(Number(form.event_date.slice(0,4)));await load();setModal(false)}catch(error){setNotice(error instanceof Error?error.message:'保存失败')}finally{setSaving(false)}};
 const remove=async()=>{if(!editing||saving||!window.confirm(`确定删除“${editing.title}”吗？`))return;setSaving(true);try{const response=await fetch(`/api/events/${editing.id}`,{method:'DELETE'});if(!response.ok)throw new Error('删除失败');await load();setModal(false)}catch(error){setNotice(error instanceof Error?error.message:'删除失败')}finally{setSaving(false)}};
 const chooseImage=async(file?:File)=>{if(!file)return;setImageBusy(true);setNotice('');try{const image=await optimizeImage(file);setForm(current=>({...current,image}))}catch(error){setNotice(error instanceof Error?error.message:'图片处理失败')}finally{setImageBusy(false)}};
 const toggleMember=(id:string)=>setForm(current=>({...current,participant_ids:current.participant_ids.includes(id)?current.participant_ids.filter(value=>value!==id):[...current.participant_ids,id]}));
 return <section className="page years-editor-page"><header className="years-editor-head"><div><p className="kicker">YEAR BY YEAR</p><h1>共同纪年</h1></div><div><p>按日期自动排序，记录参与成员、地点与可跳转的影像。</p><button onClick={openAdd}><Plus size={17}/>添加事件</button></div></header>{notice&&!modal&&<p className="years-notice">{notice}</p>}<div className="year-tabs">{availableYears.map(value=><button key={value} className={year===value?'active':''} onClick={()=>setYear(value)}>{value}</button>)}</div><div className="event-list editable-event-list">{visible.map((event,index)=>{const ids=participantsOf(event);const image=<img src={event.image} alt={`${event.title}相关图片`} loading="lazy" decoding="async"/>;return <article key={event.id}><span>{String(index+1).padStart(2,'0')}</span><div className="event-copy"><time>{event.event_date.replaceAll('-','.')}</time><h3>{event.title}</h3><p>{event.place||'地点待补充'}</p><button className="event-edit" onClick={()=>openEdit(event)}><Pencil size={13}/>编辑</button></div><div className="event-people"><small>参与人员</small><div>{ids.map(id=>{const member=members.find(item=>item.id===id);return member?<span key={id}>{member.avatar?<img src={member.avatar} alt=""/>:null}<b>{member.nickname}</b></span>:null})}</div></div><div className={`event-image ${event.image?'has-image':''}`}>{event.image?(event.link?<a href={event.link} target="_blank" rel="noreferrer" aria-label={`打开 ${event.title} 相关链接`}>{image}<ExternalLink size={16}/></a>:image):<span>NO IMAGE</span>}</div></article>})}{!loading&&!visible.length&&<div className="event-empty">这一年还没有事件，点击“添加事件”开始记录。</div>}{loading&&<div className="event-empty"><LoaderCircle className="spin"/>正在读取纪年……</div>}</div>
 {modal&&<div className="year-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!saving)setModal(false)}}><div className="year-modal" role="dialog" aria-modal="true"><header><div><p className="kicker">TIMELINE EVENT</p><h2>{editing?'编辑事件':'添加事件'}</h2></div><button onClick={()=>setModal(false)} aria-label="关闭"><X/></button></header><form onSubmit={submit}><label><span>日期 *</span><input type="date" required value={form.event_date} onChange={e=>setForm({...form,event_date:e.target.value})}/></label><label><span>标题 *</span><input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide"><span>地点</span><input maxLength={300} value={form.place} onChange={e=>setForm({...form,place:e.target.value})}/></label><fieldset className="wide"><legend>参与人员</legend><div className="member-options">{members.map(member=><label key={member.id} className={form.participant_ids.includes(member.id)?'selected':''}><input type="checkbox" checked={form.participant_ids.includes(member.id)} onChange={()=>toggleMember(member.id)}/>{member.avatar&&<img src={member.avatar} alt=""/>}<span>{member.nickname}</span></label>)}</div></fieldset><label className="wide"><span>事件图片（可选）</span><div className="event-image-input">{form.image?<img src={form.image} alt="预览"/>:<ImagePlus/>}<div><b>{imageBusy?'正在处理图片……':form.image?'更换图片':'选择图片'}</b><small>自动转为 WebP，最大 220KB</small></div><input type="file" accept="image/*" disabled={imageBusy||saving} onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value='';void chooseImage(file)}}/></div>{form.image&&<button type="button" className="remove-event-image" onClick={()=>setForm({...form,image:'',link:''})}>移除图片</button>}</label>{form.image&&<label className="wide"><span>图片跳转链接（可选）</span><input type="url" value={form.link} onChange={e=>setForm({...form,link:e.target.value})} placeholder="https://www.bilibili.com/…"/></label>}{notice&&<p className="years-form-error wide">{notice}</p>}<div className="year-form-actions wide">{editing&&<button type="button" className="delete-event" onClick={remove}><Trash2 size={15}/>删除</button>}<span/><button type="button" onClick={()=>setModal(false)}>取消</button><button className="save-event" disabled={saving||imageBusy}>{saving?<LoaderCircle className="spin"/>:null}保存</button></div></form></div></div>}
 </section>
}
